name: votingsystem
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  cupertino_icons: ^1.0.8
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Background.png
    - assets/Logo.png
    - assets/Flow_3.json
    - assets/Loading.json
    - assets/Vote_Loading.json
    - assets/Ant.jpg
    - assets/Ara.jpg
    - assets/Hari.jpg
    - assets/Karan.jpg
    - assets/Flow_2.json
    - assets/Fingerprint.png
